import { test, expect } from '@playwright/test';

test('DashBoard Functionality Verification', async ({ page }) => {
  await page.goto('https://prople.pro//login');
  await page.getByRole('link', { name: 'Login' }).click();
  await page.getByRole('textbox', { name: 'john@company.com' }).click();
  await page.getByRole('textbox', { name: 'john@company.com' }).fill('Praveen.m@spearsoftech.com');
  await page.getByRole('textbox', { name: '••••••••' }).click();
  await page.getByRole('textbox', { name: '••••••••' }).fill('Vihansh77**');
  await page.getByRole('button', { name: 'Sign In' }).click();
  await page.getByRole('link', { name: 'Dashboard' }).click();
  await page.getByRole('heading', { name: 'Hey Manda Praveen Kumar,' }).click();
  await page.getByText(':43:44 PM').click();
  await page.getByRole('button', { name: 'Clock In' }).click();
  await page.getByRole('button', { name: 'Clock In' }).click();
  await page.getByRole('button', { name: 'Send A Message' }).click();
  await page.getByRole('button', { name: 'Close' }).click();
  await page.locator('div').filter({ hasText: 'StatusClocked OutTotal' }).nth(3).click();
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.getByRole('heading', { name: 'My WFH Requests' }).click();
  await page.getByRole('button', { name: '+ New Request' }).click();
  await page.getByRole('button', { name: '25' }).click();
  await page.getByRole('button').filter({ hasText: /^$/ }).nth(3).click();
  await page.getByText('M', { exact: true }).nth(1).click();
  await page.getByRole('button', { name: 'View All' }).nth(1).click();
  await page.getByRole('button', { name: 'Close' }).click();
  await page.getByRole('button', { name: 'View All' }).nth(1).press('ArrowDown');
  await page.getByRole('button', { name: 'View All' }).nth(1).press('ArrowDown');
  await page.getByRole('button', { name: 'View All' }).nth(1).press('ArrowDown');
  await page.getByRole('button', { name: 'View All' }).nth(1).press('ArrowDown');
  await page.getByRole('button', { name: 'View All' }).nth(1).press('ArrowDown');
  await page.locator('div').filter({ hasText: /^0$/ }).nth(2).click();
  await page.locator('div').filter({ hasText: /^0$/ }).nth(4).click();
  await page.locator('div:nth-child(3) > .relative > .absolute').click();
  await page.locator('div').filter({ hasText: /^1$/ }).nth(1).click();
  await page.locator('div:nth-child(5) > .relative > .absolute').click();
  const page1Promise = page.waitForEvent('popup');
  await page.getByRole('button', { name: 'Grant Permission' }).click();
  const page1 = await page1Promise;
  await page.locator('.rounded-lg > .lf-player-container').click();
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.getByRole('heading', { name: 'Holidays (1)' }).click();
  await page.getByRole('heading', { name: 'Holidays (1)' }).click();
  await page.getByText('Thursday #CHRISTMAS').click();
  await page.getByRole('button', { name: 'Show All Holidays' }).click();
  await page.locator('.fixed.inset-0').click();
  await page.getByRole('button', { name: 'Show All Holidays' }).press('ArrowDown');
  await page.getByRole('button', { name: 'Show All Holidays' }).press('ArrowDown');
  await page.getByRole('button', { name: 'Show All Holidays' }).press('ArrowDown');
  await page.getByRole('button', { name: 'Show All Holidays' }).press('ArrowDown');
  await page.getByRole('button', { name: 'Show All Holidays' }).press('ArrowDown');
  await page.getByRole('button', { name: 'Show All Holidays' }).press('ArrowDown');
  await page.getByRole('button', { name: 'Show All Holidays' }).press('ArrowDown');
  await page.getByRole('button', { name: 'Show All Holidays' }).press('ArrowDown');
  await page.getByRole('button', { name: 'Show All Holidays' }).press('ArrowDown');
  await page.getByRole('button', { name: 'Show All Holidays' }).press('ArrowDown');
  await page.getByRole('button', { name: 'Show All Holidays' }).press('ArrowDown');
  await page.getByRole('button', { name: 'Show All Holidays' }).press('ArrowDown');
  await page.getByRole('heading', { name: 'Quick Links' }).click();
  await page.getByRole('link', { name: 'Apply Leave' }).click();   
});