import { test, expect } from '@playwright/test';

test('wmqa2 Bulk placing order', async ({ page }) => {
  await page.goto('https://wmqa2.wm.com/');
  await page.getByTestId('LoginPopover-Button').click();
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('ccsatyatest9@gmail.com');
  await page.getByRole('textbox', { name: 'Email' }).press('Tab');
  await page.getByRole('textbox', { name: 'Password' }).fill('SatyAKotA1');
  await page.getByTestId('TextInputForm').getByTestId('ButtonPrimary').click();
  await page.getByTestId('close-all-button').getByTestId('Button').click();
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.getByTestId('bulk_trash_pickup').click();
  await page.locator('.MuiBox-root.css-psawk').click();
  await page.getByTestId('PageLayout-mainContent').press('ArrowDown');
  await page.getByTestId('PageLayout-mainContent').press('ArrowDown');
  await page.getByTestId('PageLayout-mainContent').press('ArrowDown');
  await page.locator('[id="panel-Mattress/Box Spring-header"]').getByRole('button', { name: 'DN Increase Inactive' }).click();
  await page.getByRole('button', { name: 'Outdoor and Sports Icon_Arrow', exact: true }).click();
  await page.getByRole('button', { name: 'DN Increase Inactive' }).nth(4).click();
  await page.getByRole('button', { name: 'DN Increase Inactive' }).nth(4).press('ArrowUp');
  await page.getByRole('button', { name: 'DN Increase Inactive' }).nth(4).press('ArrowUp');
  await page.getByRole('button', { name: 'DN Increase Inactive' }).nth(4).press('ArrowUp');
  await page.getByRole('button', { name: 'DN Increase Inactive' }).nth(4).press('ArrowUp');
  await page.getByRole('button', { name: 'DN Increase Inactive' }).nth(4).press('ArrowUp');
  await page.getByRole('button', { name: 'DN Increase Inactive' }).nth(4).press('ArrowUp');
  await page.getByRole('button', { name: 'DN Increase Inactive' }).nth(4).press('ArrowUp');
  await page.getByRole('button', { name: 'Total Items (2) Icon_Arrow' }).click();
  await page.getByTestId('PricingCard-continue-button').click();
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.getByTestId('DatePicker-inline-calendar-wrapper').locator('label').click();
  await page.getByRole('button', { name: 'Next month' }).click();
  await page.getByRole('gridcell', { name: '10' }).click();
  await page.getByTestId('PageLayout-mainContent').press('ArrowDown');
  await page.getByTestId('PageLayout-mainContent').press('ArrowDown');
  await page.getByTestId('PageLayout-mainContent').press('ArrowDown');
  await page.getByTestId('PageLayout-mainContent').press('ArrowDown');
  await page.getByTestId('PageLayout-mainContent').press('ArrowDown');
  await page.getByTestId('PageLayout-mainContent').press('ArrowDown');
  await page.getByTestId('PageLayout-mainContent').press('ArrowDown');
  await page.getByRole('textbox', { name: 'unit number, apt number, gate' }).click();
  await page.getByRole('textbox', { name: 'unit number, apt number, gate' }).fill('Satya-Test-BP-QA2');
  await page.getByRole('textbox', { name: 'unit number, apt number, gate' }).press('ArrowDown');
  await page.getByRole('textbox', { name: 'unit number, apt number, gate' }).press('ArrowDown');
  await page.getByRole('textbox', { name: 'unit number, apt number, gate' }).press('ArrowDown');
  await page.getByRole('textbox', { name: 'unit number, apt number, gate' }).press('ArrowDown');
  await page.getByRole('textbox', { name: 'unit number, apt number, gate' }).press('ArrowDown');
  await page.getByRole('textbox', { name: 'unit number, apt number, gate' }).press('ArrowDown');
  await page.getByRole('textbox', { name: 'unit number, apt number, gate' }).press('ArrowDown');
  await page.getByRole('textbox', { name: 'unit number, apt number, gate' }).press('ArrowDown');
  await page.getByRole('textbox', { name: 'unit number, apt number, gate' }).press('ArrowDown');
  await page.getByTestId('bulkPickupForm').click();
  await page.getByTestId('PageLayout-mainContent').press('ArrowDown');
  await page.getByTestId('PageLayout-mainContent').press('ArrowDown');
  await page.getByTestId('PageLayout-mainContent').press('ArrowDown');
  await page.getByTestId('PageLayout-mainContent').press('ArrowDown');
  await page.getByTestId('PageLayout-mainContent').press('ArrowDown');
  await page.getByTestId('PageLayout-mainContent').press('ArrowDown');
  await page.getByTestId('PageLayout-mainContent').press('ArrowDown');
  await page.getByRole('checkbox', { name: 'not checked' }).check();
  await page.getByRole('checkbox', { name: 'checked' }).press('ArrowDown');
  await page.getByRole('checkbox', { name: 'checked' }).press('ArrowDown');
  await page.getByRole('checkbox', { name: 'checked' }).press('ArrowDown');
  await page.getByRole('checkbox', { name: 'checked' }).press('ArrowDown');
  await page.getByTestId('PricingCard-continue-button').click();
  await page.locator('.MuiBox-root.css-psawk').click();
  await page.getByTestId('PageLayout-mainContent').press('ArrowDown');
  await page.locator('label').filter({ hasText: '5 Stars' }).click();
  await page.locator('.jss376').click();
  await page.getByTestId('PageLayout-mainContent').press('ArrowDown');
  await page.getByTestId('PageLayout-mainContent').press('ArrowDown');
  await page.getByTestId('PageLayout-mainContent').press('ArrowDown');
  await page.getByTestId('PageLayout-mainContent').press('ArrowDown');
  await page.getByTestId('PageLayout-mainContent').press('ArrowDown');
  await page.getByTestId('PageLayout-mainContent').press('ArrowDown');
  await page.getByTestId('PageLayout-mainContent').press('ArrowDown');
  await page.getByTestId('PageLayout-mainContent').press('ArrowDown');
  await page.getByTestId('PageLayout-mainContent').press('ArrowUp');
  await page.getByTestId('PageLayout-mainContent').press('ArrowUp');
  await page.getByTestId('PageLayout-mainContent').press('ArrowUp');
  await page.getByTestId('PageLayout-mainContent').press('ArrowUp');
  await page.getByTestId('PageLayout-mainContent').press('ArrowUp');
  await page.getByTestId('PageLayout-mainContent').press('ArrowUp');
  await page.getByTestId('PageLayout-mainContent').press('ArrowUp');
  await page.getByTestId('PageLayout-mainContent').press('ArrowUp');
  await page.getByTestId('PageLayout-mainContent').press('ArrowUp');
  await page.getByTestId('PageLayout-mainContent').press('ArrowUp');
  await page.getByTestId('PageLayout-mainContent').press('ArrowUp');
  await page.getByTestId('PageLayout-mainContent').press('ArrowUp');
  await page.getByTestId('PageLayout-mainContent').press('ArrowDown');
  await page.getByTestId('PageLayout-mainContent').press('ArrowDown');
  await page.waitForTimeout(5000);
  await page.getByTestId('EmbeddedQuestions-Submit').click();
  await page.waitForTimeout(5000);
});